baseURL = ""
languageCode = "en-us"
title = "Making a Website with R and the Blogdown Package"
theme = "hugo-whisper-theme"
copyright = "&copy; Deniz Çivril, {year}"

enableEmoji = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Stories"
    url = "/stories"
    weight = 2

[[menu.main]]
    name = "Tutorial"
    url = "/tutorial"
    weight = 3

[params]
  mainSections = ["stories", "tutorial"]
  google_analytics_id=""
  homepage_button_link = '/tutorial'
  homepage_button_text = 'Start the tutorial'
  homepage_intro = ''
  homepage_image = ''

  ## You can enable to add anchor links to header elements
  enable_anchor_link = false

  [params.homepage_meta_tags]
    meta_description = "Making a Website with R and the Blogdown Package"
    meta_og_title = "Making a Website with R and the Blogdown Package"
    meta_og_type = "website"
    meta_og_url = "https://makingwebsiteswithr.netlify.com"
    meta_og_image = ""
    meta_og_description = "Making a Website with R and the Blogdown Package"
    meta_twitter_card = "summary"
    meta_twitter_site = "@denizCvrl"
    meta_twitter_creator = "@denizCvrl"

  [params.logo]
      mobile = "/images/icon-32.png"
      standard  = "/images/icon-512.png"

  [markup.goldmark.renderer]
   unsafe= true

